name: Python formatting check with Black

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  black:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install required Python packages
      run: python3.8 -m pip install black --user
    - name: Check formatting with Black
      run: python3.8 -m black --check .
